= Spring MVC

* 부모인 Root ApplicationContext는 자식인 Servlet ApplicationContext의 Bean을 참조할 수 없지만 그 반대는 가능하다.
* web.xml은 servlet 환경에 존재
* / -> 기본 Servlet
* dependency <scope> provided면 패키징 할 때는 포함 안됨. -> 나중에 제공될 것으로 추측하기때문에

== Controller
.Controller
* MVC 패턴에서 Controller 역할
** 요청 처리 및 흐름 제어 담당
* Front Controller 패턴에서 Command interface 구현 클래스에 해당
** 실제 웹 요청을 처리하는 역할

=== Controller 구현
.@Controller
* stereo type bean 중 하나: component scan 과정을 통해 자동으로 bean 등록
* Meta Annotation
** Meta Annotation 찾아보기

=== Controller 구현 2
.@RestController
* @RestController = @Controller + @ResponseBody
* @Controller가 view 이름을 반환하면 ViewResolver가 view를 처리하는 반면
* @RestController는 ViewResolver가 아닌 HttpMessageConverter가 응답 객체를 처리
----
@RestController
@RequestMapping("/persons")
public class PersonController {
    /*
            GET /persons/12345

            HTTP/1.1 200 OK
            Content-type: application/json;charset=UTF-8

            {
                "name": "dongmyo",
                "age": 19,
                "address": "Ulsan, Korea"
            }
     */
    @GetMapping("/{id}")
    public Person getPerson(@PathVariable Long id) {
        // ...
    }

    /*
            POST /persons
            {
                "name": "dongmyo",
                "age": 19,
                "address": "Ulsan, Korea"
            }

            HTTP/1.1 201 Created
     */
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public void add(@RequestBody Person person) {
        // ...
    }
}
----

== Request Mapping
.@RequestMapping
* 요청을 Controller 메서드에 Mapping

=== @RequestMapping을 통한 URL Mapping

=== @RequestMapping을 통한 HTTP Method Mapping

=== Request Mapping(w/params)

.request parameter와 연결하는 방법
* id parameter가 있는 경우에만
----
@RequestMapping(method = RequestMethod.GET, params = { "id" })
----
* id parameter가 없는 경우에만
----
@GetMapping(params = { "!id" })
----
* type parameter 값이 raw 인 경우에만
----
@GetMapping(params = "type=raw")
----
* type parameter 값이 raw가 아닌 경우에만
----
@GetMapping(params = "type!=raw")
----

=== Controller Method 에서 사용 가능한 Method Argument
* HttpServletRequest, HttpServletResponse, HttpSession, WebRequest
** HttpServletRequest : 파일 업로드에 자주 사용(Stream 사용, 메모리 면에서 유리함)
** HttpServletResponse : 파일 다운로드에 자주 사용.
* Locale
** 국제화와 지역화를 통해 언어, 문자, 화폐, 시간등에 대해 어떻게 표시할 지 정의한 매개 변수의 모음
* InputStream, OutputStream, Reader, Writer
* @PathVariable, @RequestParam, @RequetHeader, @CookieValue, @Value
* Map, Model, ModelMap, @ModelAttribute, @RequestBody
* Errors, BindingResult, ...

=== Controller Method에서 사용 가능한 return type
* ModelAndView, View
* Map, Model, ModelMap
* String
* void
* @ResponseBody
* POJO
** DTO??

== Model 이용하기

=== Model로 이용할 수 있는 type
* java.util.Map interface
* org.springframework.ui.Model interface
* org.springframework.ui.ModelMap class

=== 실제 처리되는 내용
* Model에 설정한 속성(attribute)이 View에 request.attribute 로 전달됨

=== ModelAndView

* ModelAndView = Model + View
----
@GetMapping("/some-request")
public ModelAndView doSomething() {
    ModelAndView mav = new ModelAndView("viewName");
    mav.addObject("name", "value");
    // ...

    return mav;
}
----

=== 요청 parameter 받아오기(@RequestParam)

.@RequestParam
* 요청 URL의 Query String을 처리하기 위한 어노테이션
* 요청 URL
----
GET http://localhost:8080/persons?order=-createdAt
----
* Controller Method
----
@GetMapping("/persons")
public List<Person> getPersons(@RequestParam(name="order") String order) {
    // ...
}
----

=== 요청 URL의 가변 인자 가져오기(@PathVariable)

.@PathVariable
* 요청 URL의 Resource(Path)을 처리하기 위한 어노테이션
** @RequestMapping 의 path 에 변수명을 입력받기 위한 place holder 가 필요함

=== 요청 Header 값 읽어오기(@RequestHeader)

.@RequestHeader
* 요청의 HTTP 헤더를 처리하기 위한 어노테이션
* 요청
----
GET /some-request HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
----
* Controller Method
----
@GetMapping("/some-request")
public List<User> getUsers(@RequestHeader(name = "User-Agent") String userAgent) {
// ...
}
----

=== Cookie 값 읽어오기(@CookieValue)

.@CookieValue
* HTTP 쿠키를 처리하기 위한 어노테이션

== 예외처리

=== @Controller에서 예외 처리
* @ExceptionHandler + @ResponseBody + HttpMessageConverter
** Json으로 받고 싶을 때 사용
----
@ExceptionHandler(Exception.class)
@ResponseBody
public ErrorDto handleException(Exception ex) {
    // ...
    // 예외를 처리하고 에러 메세지를 담은 `ErrorDto` 객체를 생성해서 반환
    return errorDto;
}
----
* 예시 : PostNotFoundException 이 throw 되면 실행됨
----
@ExceptionHandler(PostNotFoundException.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    public String handleException(PostNotFoundException postNotFoundException, Model model) {
        model.addAttribute("exception", postNotFoundException);
        return "error";
    }
----

=== 전역 예외 처리 (Global Exception Handling)

.@ControllerAdvice
* @Component의 일종 - component scanning 과정에서 자동으로 빈 등록
** 현업에서 자주 씀
----
@ControllerAdvice
public class WebControllerAdvice {
    @ExceptionHandler({ UserNotFoundException.class, PostNotFoundException.class })
    public String handleException(Exception ex, Model model) {
        log.error("resource not found", ex);
        model.addAttribute("exception", ex);
        return "error";
    }
}
----

== Validation

=== Bean Validation 적용
* Controller Method signature 에서
** 요청 객체에 @Valid 또는 @Validated annotation 적용하고
** 바로 그 다음 argument로 BindingResult 또는 Errors 객체를 선언한 후
* Controller Method 본문에서
** 앞서 선언한 BindingResult 또는 Errors 객체를 이용해서 validation 결과 확인
* 예시 :
----
public String modifyUser(@Valid @ModelAttribute UserModifyRequest userRequest,
                         BindingResult bindingResult) {
    if (bindingResult.hasErrors()) {
        throw new ValidationFailedException(bindingResult);
    }

    // ...
}
----







---
.RestAPI
* post : 객체 리소스 등록
* put : 객체 리소스 등록 or 수정(전부)
* patch : 객체의 한 부분만 수정

.put은 수정일까?
* put은 등록, 수정. 멱등성이 있어야 함.
** 객체의 모든 변수를 수정
** 멱등성 : 상태가 같아야 한다. 결과가 같아야 한다.
*** 없는 경우 생성, 있는 경우 수정
