POST http://localhost:8080/residents/1/relationship
Content-Type: application/json

{
  "familySerialNumber": 7,
  "relationShip": "father"
}

###

PUT http://localhost:8080/residents/1/relationship/7
Content-Type: application/json

{
  "relationShip": "mother"
}

###

DELETE http://localhost:8080/residents/1/relationship/7
Content-Type: application/json

###

POST http://localhost:8080/residents/4/birth
Content-Type: application/json

{
  "targetSerialNumber": 6,
  "birthReportQualificationsCode": "비동거친족",
  "email": "testemail@naver.com",
  "phoneNumber": "010-1111-1111"
}

###

PUT http://localhost:8080/residents/4/birth/7
Content-Type: application/json

{
  "birthReportQualificationsCode": "비동거친족",
  "email": "testemail@naver.com",
  "phoneNumber": "010-1111-1111"
}

###

DELETE http://localhost:8080/residents/4/birth/7
Content-Type: application/json

