= Java Configuration

== Java Based Bean Configuration
* spring-javaconfig 라는 모듈이 개발되었으며 2009년 springframework 3.0 부터 core 에 포함하여 제공하기 시작했습니다.
* Spring IoC 컨테이너 설정을 순수한 Java 로만 작성할 수 있는 도구입니다.

== Spring JavaConfig 클래스 작성
* Spring JavaConfig 클래스에는 @Configuration 어노테이션을 설정해야 합니다.
* Spring JavaConfig 클래스에는 @Bean 어노테이션을 설정한 메소드로 구성됩니다.
* beans.xml과 MainConfig 둘 다 Bean 등록할 경우 beans.xml이 우선 등록되고 MainConfig의 Bean은 등록되지 않는다.

== Bean Dependencies

=== 메서드 파라미터 전달
[source]
----
@Configuration
public class JavaConfig {
    @Bean
    public ARepository aRepository() {
        return new ARepositoryImpl();
    }

    @Bean
    public AService aService(ARepository aRepository) {
        return new AService(aRepository);
    }
}
----

=== 메서드 호출
[source]
----
@Configuration
public class JavaConfig {
    @Bean
    public ARepository aRepository() {
        return new ARepositoryImpl();
    }

    // with method parameter
    @Bean
    public AService aService() {
        return new AService(aRepository());
    }
}
----


=== 메서드 호출에서 주의할 것
* 아래 코드에서 aRepository() 메소드가 두번 호출되었습니다.
* ARepository 빈은 몇개가 만들어 질까요?
* @Configuration annotation에서 의존성 주입을 위해서 호출된 메소드는 CGLIB 기술을 사용하여 scope 에따라 스프링빈을 반환합니다.
[source]
----
@Configuration
public class JavaConfig {
    @Bean
    @Scope("singleton")
    public ARepository aRepository() {
        return new ARepositoryImpl();
    }

    @Bean
    public AService aService() {
        return new AService(aRepository());
    }

    @Bean
    public BService bService() {
        return new BSergice(aRepository());
    }
}
----

=== @Autowired
* 다른 곳에서 설정된 Bean 으로 의존성 주입을 하기 위해 @Autowired annotation 을 사용할 수 있습니다.
[source]
----
@Configuration
public class JavaConfig {
    @Autowired
    private ARepository aRepository;

    @Bean
    public AService aService() {
        return new AService(aRepository);
    }

    @Bean
    public BService bService() {
        return new ASergice(aRepository);
    }
}
----

=== 생성자 주입
* 다른 곳에서 설정된 Bean 으로 의존성 주입을 하기 위해 생성자를 사용할 수 있습니다.
[source]
----
@Configuration
public class JavaConfig {
    @Autowired
    private ARepositoryConfig aRepositoryConfig;

    @Bean
    public AService aService() {
        return new AService(aRepositoryConfig.aRepository());
    }
}
----

=== fully qualifying 주입
[source]
----
@Configuration
public class JavaConfig {
    private final ARepository aRepository;

    public JavaConfig(ARepository aRepository) {
        this.aRepository = aRepository;
    }

    @Bean
    public AService aService() {
        return new AService(aRepository);
    }

    @Bean
    public BService bService() {
        return new BSergice(aRepository);
    }
}
----

== Bean 생성의 조건

=== @Conditional 어노테이션
* 조건에 따라 @Configuration 이나 @Bean 이 동작하거나 동작하지 않도록 설정할수 있다.(from Spring 4)
* @Conditional 은 Condition 인터페이스 구현을 설정 해야 합니다.
* Condition 인터페이스는 matches 메소드를 제공하는데. 반환값이 true 이면 설정은 동작합니다. 반대로 반환값이 false 이면 설정은 동작하지 않습니다.
* @Profile 어노테이션이 @Conditional 을 활용한 대표적인 예 입니다.
----
@Conditional(TestCondition.class)
    @Bean
    public GreetingService greetingService(Greeter greeter) {
        GreetingService greetingService = new GreetingService(greeter);
        return greetingProcessor;
    }
----
----
class TestCondition implements Condition {

    @Override
    public boolean matches(ConditionContext context, AnnotatedTypeMetadata metadata) {
        return true;
    }
}
----

== Bean Scanning
* Bean Scanning = Component Scanning = Classpath Scanning

=== Component Scan
* @Configuration 을 지정한 클래스에 @ComponentScan 을 설정하여 스캐닝을 활성화 할 수 있습니다.
----
@Configuration
@ComponentScan(basePackages = "com.nhnacademy.edu.springframework.greeting")
public class BeanConfig {
  // .. 생략 ..
}
----
* 아래와 같이 basepackage 를 인자로 주는 경우 @ComponentScan 전에 해당 단계에서 Bean으로 다 등록되어 @ComponentScan이 없어도 동작함
----
AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext("com.nhnacademy.edu.springframework.messagesender");
----
* 아래와 같이 할 경우 @ComponentScan이 반드시 있어야 함.
----
AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(MainConfig.class);
----
=== Stereotype annotations

.Bean Scanning의 대상이 되는 어노테이션들
* @Configuration
* @Component - 기본 스프링 관리 컴포넌트. 밑의 3개와 @Configuration 은 Component를 확장함
* @Controller - Spring Web MVC 에서 Controller, View 담당
* @Service - Service layer 의 컴포넌트 마커, Business Login 담당
* @Repository - Data Access Object를 의미하는 marker 어노테이션 (Exception Translation 기능 제공), DB 혹은 Reddis 혹은 카산드라에 Data CRUD를 담당

=== Component Scan - Filter
* @ComponentScan 어노테이션은 includeFilters 와 excludeFilters 속성으로 스캔할 대상 빈을 선별합니다.

=== includeFilters 와 excludeFilters 의 사용 예
* 정규식으로 "*Stub.*Repository " 는 포함하고 Repository.class 어노테이션이 설정된 클래스는 검색에서 제외합니다.
----
@Configuration
@ComponentScan(basePackages = "org.example",
        includeFilters = @Filter(type = FilterType.REGEX, pattern = ".*Stub.*Repository"),
        excludeFilters = @Filter(Repository.class))
public class AppConfig {
    // ...
}
----

=== Component 내부에서 Bean 사용
* @Component 클래스에서도 @Configuration 과 동일하게 @Bean 을 선언할 수 있습니다.
* @Configuration 클래스에서 작성한 것과 마찬가지로 @Scope, @Qualifier, @Lazy 등을 사용할 수 있습니다.
----
@Component
public class FactoryMethodComponent {

    @Bean
    @Qualifier("public")
    public TestBean publicInstance() {
        return new TestBean("publicInstance");
    }

    public void doWork() {
        // Component method implementation omitted
    }
}
----

=== @Component Bean 이름

* @ComponentScan 으로 @Component 빈을 설정할때 빈의 이름은 BeanNameGenerator 전략으로 생성이 됩니다.
* @Component 의 이름이 지정되지 않으면 기본 BeanNameGenerator 가 소문자화된 클래스 이름으로 생성합니다.
* 아래와 같이 설정하면 빈 이름은 simpleMovieLister 로 지정됩니다.
----
@Service
public class SimpleMovieLister {
    // ...
}
----
* 아래와 같이 이름을 지정하면 빈 이름은 myMovieLister 로 지정됩니다.
----
@Service("myMovieLister")
public class SimpleMovieLister {
    // ...
}
----

=== @Component와 @Service의 차이
* UseCase에서 각각의 Case는 각각 하나의 api로 만들어 지는데 이것들은 @Service를 붙인다.
** 즉 @Service 는 UseCase 와 api 와 관련됨.
* 목적과 의미를 잘 생각해서 어노테이션 붙여야 함.

=== @Bean 과 Stereotype Annotation 사용
* 각각 방법을 써서 등록해도 다른점은 없음
* 시스템 전체에서 공통으로 사용되는 경우 @Bean으로 등록
* Business Logic에 사용되는 경우 Stereotype Annotation(@Component)로 등록









